pipeline{
    agent any 
    tools{nodejs "14.19.0"}
    stages{
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("Build"){
            steps{
                dir("sundaes"){
                    sh "npm install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("sundaes"){
                    sh "npm test"
                }
            }
        }
    }
}